name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          brew install ninja cmake

      - name: Build universal PKG
        run: |
          scripts/build_pkg.sh --universal

      - name: Release
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Nightly Build"
          files: |
            build/TaigiTelex-*.pkg
